### ISSUE TITLE
Disable search suggestions

### ISSUE THREAD

**Issue by alex-martin-mm** [LebCit/full-screen-morphing-search#1]
Hello,

We are using Algolia Search on our blog to show real-time search suggestions. We were wondering if there's a way to disable the search suggestions offered by this plugin. Right now, we are getting two search suggestions that overlap on one another so, kindly let us know how to disable the search suggestions in this plugin.

Thanks!

Regards,
Alex

**Comment by LebCit** [comment]
Hello there,

Of course you can !
In the file `class-full-screen-morphing-search.php` remove everything from line 252 till line 282 included.
So from this `$fsmsp_ac = array( // Autocomplete.` on line 252 till `endif;` on line 282.
Hope this will help you achieve your goal.
Any comment(s) suggestion(s) for improving the plugin are welcome 😊

SYA,
LebCit.

**Comment by alex-martin-mm** [comment]
That worked perfectly. Thank you so much. :)

I am using this plugin on two different sites. But, the UI of the overlay seems to be a little different on both of them. I have hidden the **Recent Posts** and other columns using CSS on both. What could be the reason for the slightly different layouts?

I have attached screenshots showing the difference between them. Also, on Site B, the **close** button doesn't work sometimes.

Let me know if there's a way to fix this.

Thanks again!

Regards,
Alex

![site_a_search](https://user-images.githubusercontent.com/64951260/81371871-9565b480-9116-11ea-8486-a0a18376f7d1.png)

![site_b_search](https://user-images.githubusercontent.com/64951260/81371878-9991d200-9116-11ea-9728-8b9999d458e0.png)

**Comment by LebCit** [comment]
Hello Alex,

You are most welcome !
Really glad to know that you're using FSMSP.
I can't tell without inspecting site B, what may be the problem.
It could be a plugin conflict, or maybe the browser (Safari), or a script conflict, or a missing config on your side, or that you have removed/deleted something related...
Scenarios here may vary depending on what's going on / or off ...
So, if you want me to have a look, give me the link to your homepage on site B and I'll see what's going on.

SYA,
LebCit.

**Comment by alex-martin-mm** [comment]
Yeah, that makes sense.

Kindly, provide me your contact email where I can reach out to you directly.

Thanks!

**Comment by LebCit** [comment]
Hello again,

I don't know why you're asking for my email 😕
I'm not asking you for a log or anything like so.
Just the link to you site as any user would type it and go to visit.
I'll just inspect the FSMSP, and try to understand what's going on or off, without any need to log.

SYA,
LebCit.

**Comment by alex-martin-mm** [comment]
Alright, no worries. I asked you for your email because most developers have a separate support email in case there are any issues or feature requests regarding their products.

What I wanted to discuss with you were certain feature suggestions for the plugin which are not really suitable for a discussion under the 'issues' tab of a repository.

I cannot post the URLs of certain niche websites on a public forum due to their competitive nature.

Hope this helps!

Regards,
Alex
